In [1]:
#import pandas
import pandas as pd
import numpy as np

In [2]:
#import dataset
nfl_df = pd.read_csv('nfl.csv')

In [3]:
#show dataset
nfl_df

,Year,Player,Age,School,Height,Weight,Sprint_40yd,Vertical_Jump,Bench_Press_Reps,Broad_Jump,Agility_3cone,Shuttle,Drafted..tm.rnd.yr.,BMI,Player_Type,Position_Type,Position,Drafted
0,2009,Beanie Wells\WellCh00,20.0,Ohio St.,1.8542,106.594207,4.38,85.09,25.0,325.12,NaN,NaN,Arizona Cardinals / 1st / 31st pick / 2009,31.004194,offense,backs_receivers,RB,Yes
1,2009,Will Davis\DaviWi99,22.0,Illinois,1.8796,118.387609,4.84,83.82,27.0,292.10,7.38,4.45,Arizona Cardinals / 6th / 204th pick / 2009,33.510073,defense,defensive_lineman,DE,Yes
2,2009,Herman Johnson\JohnHe23,24.0,LSU,2.0066,165.107623,5.50,NaN,21.0,NaN,NaN,NaN,Arizona Cardinals / 5th / 167th pick / 2009,41.005821,offense,offensive_lineman,OG,Yes
3,2009,Rashad Johnson\JohnRa98,23.0,Alabama,1.8034,92.079251,4.49,93.98,15.0,304.80,7.09,4.23,Arizona Cardinals / 3rd / 95th pick / 2009,28.312463,defense,defensive_back,FS,Yes
4,2009,Cody Brown\BrowCo96,22.0,Connecticut,1.8796,110.676538,4.76,92.71,26.0,304.80,7.10,4.40,Arizona Cardinals / 2nd / 63rd pick / 2009,31.327425,defense,line_backer,OLB,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3472,2019,Xavier Crawford,NaN,Central Michigan,1.8034,84.821773,4.48,95.25,11.0,NaN,NaN,NaN,NaN,26.080939,defense,defensive_back,CB,No
3473,2019,Jordan Brown,NaN,South Dakota St.,1.8288,91.172066,4.51,100.33,13.0,325.12,NaN,NaN,NaN,27.260221,defense,defensive_back,CB,No
3474,2019,Corey Ballentine,NaN,Washburn,1.8034,88.904105,4.47,100.33,15.0,342.90,6.82,4.14,NaN,27.336171,defense,defensive_back,CB,No
3475,2019,Ugo Amadi,NaN,Oregon,1.7526,90.264882,4.51,82.55,18.0,292.10,7.21,4.19,NaN,29.386861,defense,defensive_back,S,No
3476,2019,Nasir Adderley,NaN,Delaware,1.8288,93.440028,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27.938336,defense,defensive_back,S,No

In [4]:
#separate Drafted..tm.rnd.yr. column
draft_df = nfl_df['Drafted..tm.rnd.yr.'].str.split('/', expand = True)
draft_df

                       0      1             2      3
0     Arizona Cardinals    1st     31st pick    2009
1     Arizona Cardinals    6th    204th pick    2009
2     Arizona Cardinals    5th    167th pick    2009
3     Arizona Cardinals    3rd     95th pick    2009
4     Arizona Cardinals    2nd     63rd pick    2009
...                  ...    ...           ...    ...
3472                 NaN    NaN           NaN    NaN
3473                 NaN    NaN           NaN    NaN
3474                 NaN    NaN           NaN    NaN
3475                 NaN    NaN           NaN    NaN
3476                 NaN    NaN           NaN    NaN

[3477 rows x 4 columns]

In [5]:
#rename drafted_df columns
# needs to be added into main DF
draft_df.columns = ['Team', 'Round', 'Overall_Pick', 'Year']
draft_df

                    Team  Round  Overall_Pick   Year
0     Arizona Cardinals    1st     31st pick    2009
1     Arizona Cardinals    6th    204th pick    2009
2     Arizona Cardinals    5th    167th pick    2009
3     Arizona Cardinals    3rd     95th pick    2009
4     Arizona Cardinals    2nd     63rd pick    2009
...                  ...    ...           ...    ...
3472                 NaN    NaN           NaN    NaN
3473                 NaN    NaN           NaN    NaN
3474                 NaN    NaN           NaN    NaN
3475                 NaN    NaN           NaN    NaN
3476                 NaN    NaN           NaN    NaN

[3477 rows x 4 columns]

In [6]:
#set column from nfl_df to variable
Player = nfl_df['Player']

In [7]:
#add player column from nfl_df to drafted_df
combine_df = draft_df.join(Player)
combine_df

                    Team  Round  Overall_Pick   Year                   Player
0     Arizona Cardinals    1st     31st pick    2009    Beanie Wells\WellCh00
1     Arizona Cardinals    6th    204th pick    2009      Will Davis\DaviWi99
2     Arizona Cardinals    5th    167th pick    2009  Herman Johnson\JohnHe23
3     Arizona Cardinals    3rd     95th pick    2009  Rashad Johnson\JohnRa98
4     Arizona Cardinals    2nd     63rd pick    2009      Cody Brown\BrowCo96
...                  ...    ...           ...    ...                      ...
3472                 NaN    NaN           NaN    NaN          Xavier Crawford
3473                 NaN    NaN           NaN    NaN             Jordan Brown
3474                 NaN    NaN           NaN    NaN         Corey Ballentine
3475                 NaN    NaN           NaN    NaN                Ugo Amadi
3476                 NaN    NaN           NaN    NaN           Nasir Adderley

[3477 rows x 5 columns]

In [8]:
combine_df.loc[:,['Year', 'Player', 'Team', 'Round', 'Overall_Pick']]

       Year                   Player                Team  Round  Overall_Pick
0      2009    Beanie Wells\WellCh00  Arizona Cardinals    1st     31st pick
1      2009      Will Davis\DaviWi99  Arizona Cardinals    6th    204th pick
2      2009  Herman Johnson\JohnHe23  Arizona Cardinals    5th    167th pick
3      2009  Rashad Johnson\JohnRa98  Arizona Cardinals    3rd     95th pick
4      2009      Cody Brown\BrowCo96  Arizona Cardinals    2nd     63rd pick
...     ...                      ...                 ...    ...           ...
3472    NaN          Xavier Crawford                 NaN    NaN           NaN
3473    NaN             Jordan Brown                 NaN    NaN           NaN
3474    NaN         Corey Ballentine                 NaN    NaN           NaN
3475    NaN                Ugo Amadi                 NaN    NaN           NaN
3476    NaN           Nasir Adderley                 NaN    NaN           NaN

[3477 rows x 5 columns]

In [9]:
# add school
combine_df['School'] = nfl_df['School']
combine_df

,Team,Round,Overall_Pick,Year,Player,School
0,Arizona Cardinals,1st,31st pick,2009,Beanie Wells\WellCh00,Ohio St.
1,Arizona Cardinals,6th,204th pick,2009,Will Davis\DaviWi99,Illinois
2,Arizona Cardinals,5th,167th pick,2009,Herman Johnson\JohnHe23,LSU
3,Arizona Cardinals,3rd,95th pick,2009,Rashad Johnson\JohnRa98,Alabama
4,Arizona Cardinals,2nd,63rd pick,2009,Cody Brown\BrowCo96,Connecticut
...,...,...,...,...,...,...
3472,NaN,NaN,NaN,NaN,Xavier Crawford,Central Michigan
3473,NaN,NaN,NaN,NaN,Jordan Brown,South Dakota St.
3474,NaN,NaN,NaN,NaN,Corey Ballentine,Washburn
3475,NaN,NaN,NaN,NaN,Ugo Amadi,Oregon
3476,NaN,NaN,NaN,NaN,Nasir Adderley,Delaware

In [10]:
#reorder updated combine_df
combine_df = combine_df.loc[:,['Year', 'Player', 'School', 'Round', 'Overall_Pick', 'Team']]
combine_df

,Year,Player,School,Round,Overall_Pick,Team
0,2009,Beanie Wells\WellCh00,Ohio St.,1st,31st pick,Arizona Cardinals
1,2009,Will Davis\DaviWi99,Illinois,6th,204th pick,Arizona Cardinals
2,2009,Herman Johnson\JohnHe23,LSU,5th,167th pick,Arizona Cardinals
3,2009,Rashad Johnson\JohnRa98,Alabama,3rd,95th pick,Arizona Cardinals
4,2009,Cody Brown\BrowCo96,Connecticut,2nd,63rd pick,Arizona Cardinals
...,...,...,...,...,...,...
3472,NaN,Xavier Crawford,Central Michigan,NaN,NaN,NaN
3473,NaN,Jordan Brown,South Dakota St.,NaN,NaN,NaN
3474,NaN,Corey Ballentine,Washburn,NaN,NaN,NaN
3475,NaN,Ugo Amadi,Oregon,NaN,NaN,NaN
3476,NaN,Nasir Adderley,Delaware,NaN,NaN,NaN

In [11]:
#Add drafted column from nfl_df to combine_df
combine_df['Drafted'] = nfl_df['Drafted']
combine_df

,Year,Player,School,Round,Overall_Pick,Team,Drafted
0,2009,Beanie Wells\WellCh00,Ohio St.,1st,31st pick,Arizona Cardinals,Yes
1,2009,Will Davis\DaviWi99,Illinois,6th,204th pick,Arizona Cardinals,Yes
2,2009,Herman Johnson\JohnHe23,LSU,5th,167th pick,Arizona Cardinals,Yes
3,2009,Rashad Johnson\JohnRa98,Alabama,3rd,95th pick,Arizona Cardinals,Yes
4,2009,Cody Brown\BrowCo96,Connecticut,2nd,63rd pick,Arizona Cardinals,Yes
...,...,...,...,...,...,...,...
3472,NaN,Xavier Crawford,Central Michigan,NaN,NaN,NaN,No
3473,NaN,Jordan Brown,South Dakota St.,NaN,NaN,NaN,No
3474,NaN,Corey Ballentine,Washburn,NaN,NaN,NaN,No
3475,NaN,Ugo Amadi,Oregon,NaN,NaN,NaN,No
3476,NaN,Nasir Adderley,Delaware,NaN,NaN,NaN,No

In [12]:
#
players_drafted_df = combine_df.loc[combine_df['Drafted'] == 'Yes']
players_drafted_df

,Year,Player,School,Round,Overall_Pick,Team,Drafted
0,2009,Beanie Wells\WellCh00,Ohio St.,1st,31st pick,Arizona Cardinals,Yes
1,2009,Will Davis\DaviWi99,Illinois,6th,204th pick,Arizona Cardinals,Yes
2,2009,Herman Johnson\JohnHe23,LSU,5th,167th pick,Arizona Cardinals,Yes
3,2009,Rashad Johnson\JohnRa98,Alabama,3rd,95th pick,Arizona Cardinals,Yes
4,2009,Cody Brown\BrowCo96,Connecticut,2nd,63rd pick,Arizona Cardinals,Yes
...,...,...,...,...,...,...,...
2249,2019,Ross Pierschbacher\PierRo00,Alabama,5th,153rd pick,Washington Redskins,Yes
2250,2019,Terry McLaurin\McLaTe00,Ohio St.,3rd,76th pick,Washington Redskins,Yes
2251,2019,Bryce Love\LoveBr00,Stanford,4th,112th pick,Washington Redskins,Yes
2252,2019,Dwayne Haskins\HaskDw00,Ohio St.,1st,15th pick,Washington Redskins,Yes
2253,2019,Kelvin Harmon\HarmKe00,North Carolina St.,6th,206th pick,Washington Redskins,Yes

In [13]:
#Sort drafted players df by School
players_drafted_df.sort_values(by=['School'])

,Year,Player,School,Round,Overall_Pick,Team,Drafted
544,2011,Clyde Gates\GateCl00,Abilene Christian,4th,111th pick,Miami Dolphins,Yes
40,2009,Bernard Scott\ScotBe00,Abilene Christian,6th,209th pick,Cincinnati Bengals,Yes
34,2009,Johnny Knox\KnoxJo00,Abilene Christian,5th,140th pick,Chicago Bears,Yes
1911,2017,D.J. Jones\JoneD.01,Akron,6th,198th pick,San Francisco 49ers,Yes
798,2012,Matt McCants\McCaMa00,Ala-Birmingham,6th,201st pick,New York Giants,Yes
...,...,...,...,...,...,...,...
1288,2014,Marqueston Huff\HuffMa00,Wyoming,4th,122nd pick,Tennessee Titans,Yes
1936,2017,Chase Roullier\RoulCh00,Wyoming,6th,199th pick,Washington Redskins,Yes
1356,2015,Mark Nzeocha\NzeoMa00,Wyoming,7th,236th pick,Dallas Cowboys,Yes
1855,2017,Derek Rivers\RiveDe00,Youngstown St.,3rd,83rd pick,New England Patriots,Yes
1868,2017,Avery Moss\MossAv00,Youngstown St.,5th,167th pick,New York Giants,Yes

In [14]:
players_drafted_df['Sprint_40yd'] = nfl_df['Sprint_40yd']
players_drafted_df

/var/folders/_r/0j0sqst14wj0bs0fnv6b9x840000gn/T/ipykernel_96837/2130612098.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  players_drafted_df['Sprint_40yd'] = nfl_df['Sprint_40yd']

,Year,Player,School,Round,Overall_Pick,Team,Drafted,Sprint_40yd
0,2009,Beanie Wells\WellCh00,Ohio St.,1st,31st pick,Arizona Cardinals,Yes,4.38
1,2009,Will Davis\DaviWi99,Illinois,6th,204th pick,Arizona Cardinals,Yes,4.84
2,2009,Herman Johnson\JohnHe23,LSU,5th,167th pick,Arizona Cardinals,Yes,5.50
3,2009,Rashad Johnson\JohnRa98,Alabama,3rd,95th pick,Arizona Cardinals,Yes,4.49
4,2009,Cody Brown\BrowCo96,Connecticut,2nd,63rd pick,Arizona Cardinals,Yes,4.76
...,...,...,...,...,...,...,...,...
2249,2019,Ross Pierschbacher\PierRo00,Alabama,5th,153rd pick,Washington Redskins,Yes,5.20
2250,2019,Terry McLaurin\McLaTe00,Ohio St.,3rd,76th pick,Washington Redskins,Yes,4.35
2251,2019,Bryce Love\LoveBr00,Stanford,4th,112th pick,Washington Redskins,Yes,NaN
2252,2019,Dwayne Haskins\HaskDw00,Ohio St.,1st,15th pick,Washington Redskins,Yes,5.04
2253,2019,Kelvin Harmon\HarmKe00,North Carolina St.,6th,206th pick,Washington Redskins,Yes,4.60

In [15]:
players_drafted_df['Vertical_Jump'] = nfl_df['Vertical_Jump']
players_drafted_df

/var/folders/_r/0j0sqst14wj0bs0fnv6b9x840000gn/T/ipykernel_96837/1751073243.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  players_drafted_df['Vertical_Jump'] = nfl_df['Vertical_Jump']

,Year,Player,School,Round,Overall_Pick,Team,Drafted,Sprint_40yd,Vertical_Jump
0,2009,Beanie Wells\WellCh00,Ohio St.,1st,31st pick,Arizona Cardinals,Yes,4.38,85.09
1,2009,Will Davis\DaviWi99,Illinois,6th,204th pick,Arizona Cardinals,Yes,4.84,83.82
2,2009,Herman Johnson\JohnHe23,LSU,5th,167th pick,Arizona Cardinals,Yes,5.50,NaN
3,2009,Rashad Johnson\JohnRa98,Alabama,3rd,95th pick,Arizona Cardinals,Yes,4.49,93.98
4,2009,Cody Brown\BrowCo96,Connecticut,2nd,63rd pick,Arizona Cardinals,Yes,4.76,92.71
...,...,...,...,...,...,...,...,...,...
2249,2019,Ross Pierschbacher\PierRo00,Alabama,5th,153rd pick,Washington Redskins,Yes,5.20,57.15
2250,2019,Terry McLaurin\McLaTe00,Ohio St.,3rd,76th pick,Washington Redskins,Yes,4.35,95.25
2251,2019,Bryce Love\LoveBr00,Stanford,4th,112th pick,Washington Redskins,Yes,NaN,NaN
2252,2019,Dwayne Haskins\HaskDw00,Ohio St.,1st,15th pick,Washington Redskins,Yes,5.04,72.39
2253,2019,Kelvin Harmon\HarmKe00,North Carolina St.,6th,206th pick,Washington Redskins,Yes,4.60,82.55

In [16]:
players_drafted_df['Bench_Press_Reps'] = nfl_df['Bench_Press_Reps']
players_drafted_df

/var/folders/_r/0j0sqst14wj0bs0fnv6b9x840000gn/T/ipykernel_96837/1088619391.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  players_drafted_df['Bench_Press_Reps'] = nfl_df['Bench_Press_Reps']

,Year,Player,School,Round,Overall_Pick,Team,Drafted,Sprint_40yd,Vertical_Jump,Bench_Press_Reps
0,2009,Beanie Wells\WellCh00,Ohio St.,1st,31st pick,Arizona Cardinals,Yes,4.38,85.09,25.0
1,2009,Will Davis\DaviWi99,Illinois,6th,204th pick,Arizona Cardinals,Yes,4.84,83.82,27.0
2,2009,Herman Johnson\JohnHe23,LSU,5th,167th pick,Arizona Cardinals,Yes,5.50,NaN,21.0
3,2009,Rashad Johnson\JohnRa98,Alabama,3rd,95th pick,Arizona Cardinals,Yes,4.49,93.98,15.0
4,2009,Cody Brown\BrowCo96,Connecticut,2nd,63rd pick,Arizona Cardinals,Yes,4.76,92.71,26.0
...,...,...,...,...,...,...,...,...,...,...
2249,2019,Ross Pierschbacher\PierRo00,Alabama,5th,153rd pick,Washington Redskins,Yes,5.20,57.15,20.0
2250,2019,Terry McLaurin\McLaTe00,Ohio St.,3rd,76th pick,Washington Redskins,Yes,4.35,95.25,18.0
2251,2019,Bryce Love\LoveBr00,Stanford,4th,112th pick,Washington Redskins,Yes,NaN,NaN,18.0
2252,2019,Dwayne Haskins\HaskDw00,Ohio St.,1st,15th pick,Washington Redskins,Yes,5.04,72.39,NaN
2253,2019,Kelvin Harmon\HarmKe00,North Carolina St.,6th,206th pick,Washington Redskins,Yes,4.60,82.55,18.0

In [17]:
players_drafted_df['Broad_Jump'] = nfl_df['Broad_Jump']
players_drafted_df

/var/folders/_r/0j0sqst14wj0bs0fnv6b9x840000gn/T/ipykernel_96837/2568882472.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  players_drafted_df['Broad_Jump'] = nfl_df['Broad_Jump']

,Year,Player,School,Round,Overall_Pick,Team,Drafted,Sprint_40yd,Vertical_Jump,Bench_Press_Reps,Broad_Jump
0,2009,Beanie Wells\WellCh00,Ohio St.,1st,31st pick,Arizona Cardinals,Yes,4.38,85.09,25.0,325.12
1,2009,Will Davis\DaviWi99,Illinois,6th,204th pick,Arizona Cardinals,Yes,4.84,83.82,27.0,292.10
2,2009,Herman Johnson\JohnHe23,LSU,5th,167th pick,Arizona Cardinals,Yes,5.50,NaN,21.0,NaN
3,2009,Rashad Johnson\JohnRa98,Alabama,3rd,95th pick,Arizona Cardinals,Yes,4.49,93.98,15.0,304.80
4,2009,Cody Brown\BrowCo96,Connecticut,2nd,63rd pick,Arizona Cardinals,Yes,4.76,92.71,26.0,304.80
...,...,...,...,...,...,...,...,...,...,...,...
2249,2019,Ross Pierschbacher\PierRo00,Alabama,5th,153rd pick,Washington Redskins,Yes,5.20,57.15,20.0,NaN
2250,2019,Terry McLaurin\McLaTe00,Ohio St.,3rd,76th pick,Washington Redskins,Yes,4.35,95.25,18.0,317.50
2251,2019,Bryce Love\LoveBr00,Stanford,4th,112th pick,Washington Redskins,Yes,NaN,NaN,18.0,NaN
2252,2019,Dwayne Haskins\HaskDw00,Ohio St.,1st,15th pick,Washington Redskins,Yes,5.04,72.39,NaN,NaN
2253,2019,Kelvin Harmon\HarmKe00,North Carolina St.,6th,206th pick,Washington Redskins,Yes,4.60,82.55,18.0,297.18

In [18]:
players_drafted_df['Agility_3cone'] = nfl_df['Agility_3cone']
players_drafted_df

/var/folders/_r/0j0sqst14wj0bs0fnv6b9x840000gn/T/ipykernel_96837/191875169.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  players_drafted_df['Agility_3cone'] = nfl_df['Agility_3cone']

,Year,Player,School,Round,Overall_Pick,Team,Drafted,Sprint_40yd,Vertical_Jump,Bench_Press_Reps,Broad_Jump,Agility_3cone
0,2009,Beanie Wells\WellCh00,Ohio St.,1st,31st pick,Arizona Cardinals,Yes,4.38,85.09,25.0,325.12,NaN
1,2009,Will Davis\DaviWi99,Illinois,6th,204th pick,Arizona Cardinals,Yes,4.84,83.82,27.0,292.10,7.38
2,2009,Herman Johnson\JohnHe23,LSU,5th,167th pick,Arizona Cardinals,Yes,5.50,NaN,21.0,NaN,NaN
3,2009,Rashad Johnson\JohnRa98,Alabama,3rd,95th pick,Arizona Cardinals,Yes,4.49,93.98,15.0,304.80,7.09
4,2009,Cody Brown\BrowCo96,Connecticut,2nd,63rd pick,Arizona Cardinals,Yes,4.76,92.71,26.0,304.80,7.10
...,...,...,...,...,...,...,...,...,...,...,...,...
2249,2019,Ross Pierschbacher\PierRo00,Alabama,5th,153rd pick,Washington Redskins,Yes,5.20,57.15,20.0,NaN,7.83
2250,2019,Terry McLaurin\McLaTe00,Ohio St.,3rd,76th pick,Washington Redskins,Yes,4.35,95.25,18.0,317.50,7.01
2251,2019,Bryce Love\LoveBr00,Stanford,4th,112th pick,Washington Redskins,Yes,NaN,NaN,18.0,NaN,NaN
2252,2019,Dwayne Haskins\HaskDw00,Ohio St.,1st,15th pick,Washington Redskins,Yes,5.04,72.39,NaN,NaN,NaN
2253,2019,Kelvin Harmon\HarmKe00,North Carolina St.,6th,206th pick,Washington Redskins,Yes,4.60,82.55,18.0,297.18,7.15

In [19]:
players_drafted_df['Shuttle'] = nfl_df['Shuttle']
players_drafted_df

/var/folders/_r/0j0sqst14wj0bs0fnv6b9x840000gn/T/ipykernel_96837/1564135052.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  players_drafted_df['Shuttle'] = nfl_df['Shuttle']

,Year,Player,School,Round,Overall_Pick,Team,Drafted,Sprint_40yd,Vertical_Jump,Bench_Press_Reps,Broad_Jump,Agility_3cone,Shuttle
0,2009,Beanie Wells\WellCh00,Ohio St.,1st,31st pick,Arizona Cardinals,Yes,4.38,85.09,25.0,325.12,NaN,NaN
1,2009,Will Davis\DaviWi99,Illinois,6th,204th pick,Arizona Cardinals,Yes,4.84,83.82,27.0,292.10,7.38,4.45
2,2009,Herman Johnson\JohnHe23,LSU,5th,167th pick,Arizona Cardinals,Yes,5.50,NaN,21.0,NaN,NaN,NaN
3,2009,Rashad Johnson\JohnRa98,Alabama,3rd,95th pick,Arizona Cardinals,Yes,4.49,93.98,15.0,304.80,7.09,4.23
4,2009,Cody Brown\BrowCo96,Connecticut,2nd,63rd pick,Arizona Cardinals,Yes,4.76,92.71,26.0,304.80,7.10,4.40
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2249,2019,Ross Pierschbacher\PierRo00,Alabama,5th,153rd pick,Washington Redskins,Yes,5.20,57.15,20.0,NaN,7.83,4.70
2250,2019,Terry McLaurin\McLaTe00,Ohio St.,3rd,76th pick,Washington Redskins,Yes,4.35,95.25,18.0,317.50,7.01,4.15
2251,2019,Bryce Love\LoveBr00,Stanford,4th,112th pick,Washington Redskins,Yes,NaN,NaN,18.0,NaN,NaN,NaN
2252,2019,Dwayne Haskins\HaskDw00,Ohio St.,1st,15th pick,Washington Redskins,Yes,5.04,72.39,NaN,NaN,NaN,NaN
2253,2019,Kelvin Harmon\HarmKe00,North Carolina St.,6th,206th pick,Washington Redskins,Yes,4.60,82.55,18.0,297.18,7.15,4.32

In [20]:
#Count for each school for drafted players
players_drafted_df['School'].value_counts()

Alabama               76
Ohio St.              62
LSU                   61
Florida               58
USC                   54
                      ..
Bloomsburg             1
Saginaw Valley St.     1
Hillsdale              1
Presbyterian           1
Arizona State          1
Name: School, Length: 205, dtype: int64

In [21]:
#add drafted result column to undrafted players df
players_undrafted_df = combine_df.loc[combine_df['Drafted'] == 'No']
players_undrafted_df

,Year,Player,School,Round,Overall_Pick,Team,Drafted
2254,NaN,Jahi Word-Daniels\WordJa99,Georgia Tech,NaN,NaN,NaN,No
2255,NaN,John Parker Wilson\WilsJo01,Alabama,NaN,NaN,NaN,No
2256,NaN,Edwin Williams\WillEd02,Maryland,NaN,NaN,NaN,No
2257,NaN,Drew Willy\WillDr00,Buffalo,NaN,NaN,NaN,No
2258,NaN,Derek Walker\WalkDe98,Illinois,NaN,NaN,NaN,No
...,...,...,...,...,...,...,...
3472,NaN,Xavier Crawford,Central Michigan,NaN,NaN,NaN,No
3473,NaN,Jordan Brown,South Dakota St.,NaN,NaN,NaN,No
3474,NaN,Corey Ballentine,Washburn,NaN,NaN,NaN,No
3475,NaN,Ugo Amadi,Oregon,NaN,NaN,NaN,No
3476,NaN,Nasir Adderley,Delaware,NaN,NaN,NaN,No

In [22]:
#sort undrafted players by school
players_undrafted_df.sort_values(by=['School'])

,Year,Player,School,Round,Overall_Pick,Team,Drafted
3179,NaN,Jalen Robinette\RobiJa02,Air Force,NaN,NaN,NaN,No
3204,NaN,Jerome Lane\LaneJe01,Akron,NaN,NaN,NaN,No
2876,NaN,Adrian Hubbard\HubbAd00,Alabama,NaN,NaN,NaN,No
3355,NaN,Dashawn Hand,Alabama,NaN,NaN,NaN,No
3029,NaN,Chris Jones,Alabama,NaN,NaN,NaN,No
...,...,...,...,...,...,...,...
3384,NaN,Andrew Wingard\WingAn00,Wyoming,NaN,NaN,NaN,No
2661,NaN,Patrick Witt,Yale,NaN,NaN,NaN,No
3009,NaN,Tyler Varga,Yale,NaN,NaN,NaN,No
2746,NaN,Lamar Mady\MadyLa00,Youngstown St.,NaN,NaN,NaN,No
2401,NaN,Donald Jones\JoneDo00,Youngstown St.,NaN,NaN,NaN,No

In [23]:
#Count of each school for undrafted players
players_undrafted_df['School'].value_counts()

LSU              34
USC              25
Alabama          25
Michigan St.     22
Florida St.      21
                 ..
Lehigh            1
Arkansas St.      1
Louisiana St      1
Southern Utah     1
Delaware          1
Name: School, Length: 206, dtype: int64

In [24]:
#Delete unnecessary columns from undrafted players df
del players_undrafted_df['Round']
del players_undrafted_df['Overall_Pick']
del players_undrafted_df['Team']

In [25]:
players_undrafted_df

     Year                       Player            School Drafted
2254  NaN   Jahi Word-Daniels\WordJa99      Georgia Tech      No
2255  NaN  John Parker Wilson\WilsJo01           Alabama      No
2256  NaN      Edwin Williams\WillEd02          Maryland      No
2257  NaN          Drew Willy\WillDr00           Buffalo      No
2258  NaN        Derek Walker\WalkDe98          Illinois      No
...   ...                          ...               ...     ...
3472  NaN              Xavier Crawford  Central Michigan      No
3473  NaN                 Jordan Brown  South Dakota St.      No
3474  NaN             Corey Ballentine          Washburn      No
3475  NaN                    Ugo Amadi            Oregon      No
3476  NaN               Nasir Adderley          Delaware      No

[1223 rows x 4 columns]

In [26]:
# export CSVs
players_drafted_df.to_csv('Drafted_Players')
players_undrafted_df.to_csv('Undrafted_players')

In [27]:
draft_df

                    Team  Round  Overall_Pick   Year
0     Arizona Cardinals    1st     31st pick    2009
1     Arizona Cardinals    6th    204th pick    2009
2     Arizona Cardinals    5th    167th pick    2009
3     Arizona Cardinals    3rd     95th pick    2009
4     Arizona Cardinals    2nd     63rd pick    2009
...                  ...    ...           ...    ...
3472                 NaN    NaN           NaN    NaN
3473                 NaN    NaN           NaN    NaN
3474                 NaN    NaN           NaN    NaN
3475                 NaN    NaN           NaN    NaN
3476                 NaN    NaN           NaN    NaN

[3477 rows x 4 columns]